models.py
from __init__ import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(90), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)
    comments = db.relationship('Comment', backref='author', lazy=True)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False)
    content = db.Column(db.Text, nullable=False)
    author_name = db.Column(db.String(20), db.ForeignKey('user.username'), nullable=False)
    comments = db.relationship('Comment', backref='post', lazy=True)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_posted = db.Column(db.DateTime, nullable=False)
    content = db.Column(db.Text, nullable=False)
    author_name = db.Column(db.String(20), db.ForeignKey('user.username'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'), nullable=False)

__init__.py
from flask import Flask
import flask_login
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def create_app():
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.Config')

    login_manager = flask_login.LoginManager()
    login_manager.init_app(app)

    db.init_app(app)

    from models import User

    @login_manager.user_loader
    def user_loader(user_id):
        return User.query.get(int(user_id))

    with app.app_context():
        db.create_all()

        from routes import content, auth

        app.register_blueprint(content.content_)
        app.register_blueprint(auth.auth_)

        return app

app.py
from __init__ import create_app
import os


app = create_app()

APP_PORT = app.config["APP_PORT"]
DEBUG = app.config["DEBUG"]

if __name__ == "__main__":
    app.secret_key = os.urandom(25)
    app.run(debug=DEBUG, host='0.0.0.0', port=APP_PORT, threaded=True)

routes/auth.py
from flask import render_template, Blueprint, redirect, url_for, request
import flask_login
from werkzeug.security import generate_password_hash, check_password_hash
from models import User
from __init__ import db
from utils import routes_utils
from utils import verification_utils

auth_ = Blueprint("auth", __name__, template_folder='template', static_folder='static')


@auth_.route("/register")
def register():
    if flask_login.current_user.is_authenticated:
        return redirect(url_for("content.home"))
    else:
        return render_template("register.html")


@auth_.route("/login")
def login():
    if flask_login.current_user.is_authenticated:
        return redirect(url_for("content.home"))
    else:
        return render_template("login.html")


@auth_.route("/register/process", methods=["POST"])
def register_process():
    if not request.form["name"] or not request.form["password"]:
        return routes_utils.render_register("Password or Username can't be empty")
    else:
        name = request.form["name"]
        password = request.form["password"]

        if User.query.filter_by(username=name).first():
            return routes_utils.render_register("Username already taken")
        else:
            if verification_utils.check_password(password) and verification_utils.check_username(name):
                new_user = User(username=name, password=generate_password_hash(password, method="sha256"))

                db.session.add(new_user)
                db.session.commit()

                return routes_utils.render_home(None, "Succesfully created an account")
            else:
                message = "Invalid username or password see our guidline about creating accounts"
                return routes_utils.render_register(message)


@auth_.route("/login/process", methods=["POST"])
def login_process():
    name = request.form.get("name")
    password = request.form.get("password")

    user = User.query.filter_by(username=name).first()

    if not user or not check_password_hash(user.password, password):
        return routes_utils.render_login("Invalid username or password")

    else:
        flask_login.login_user(user)

        return redirect(url_for("content.home"))


@auth_.route("/logout", methods=["POST", "GET"])
@flask_login.login_required
def logout():
    flask_login.logout_user()

    return redirect(url_for("content.home"))

routes/content.py
from flask import Blueprint, redirect, url_for, request
import flask_login
from utils import routes_utils
from utils import social_utils
from utils import verification_utils
from flask import current_app as app

content_ = Blueprint("content", __name__, template_folder='template', static_folder='static')


@content_.route("/")
def home():
    return routes_utils.render_home(None, None)


@content_.route("/profile")
@flask_login.login_required
def profile():
    return routes_utils.render_profile()


@content_.route("/post")
@flask_login.login_required
def post():
    return routes_utils.render_post(None)


@content_.route("/post_content/<post_id>")
@flask_login.login_required
def post_content(post_id):
    return routes_utils.render_post_content(post_id, None)


@content_.route("/post/commit", methods=["POST"])
@flask_login.login_required
def post_commit():
    if request.form["post-text"] and request.form["post-title"]:
        text = request.form["post-text"]
        title = request.form["post-title"]

        POST_TITLE_MIN_LENGTH = app.config["POST_TITLE_MIN_LENGTH"]
        POST_TITLE_MAX_LENGTH = app.config["POST_TITLE_MAX_LENGTH"]
        POST_CONTENT_MIN_LENGTH = app.config["POST_CONTENT_MIN_LENGTH"]
        POST_CONTENT_MAX_LENGTH = app.config["POST_CONTENT_MAX_LENGTH"]

        if verification_utils.check(text, POST_CONTENT_MAX_LENGTH, POST_CONTENT_MIN_LENGTH, None) and \
                verification_utils.check(title, POST_TITLE_MAX_LENGTH, POST_TITLE_MIN_LENGTH, None):
            username = flask_login.current_user.username

            social_utils.create_post(title, text, username)

            return redirect(url_for("content.home"))
        else:
            return routes_utils.render_post("Invalid title or text")
    else:
        return routes_utils.render_post("Post title and text can't be empty")


@content_.route("/comment/commit/<post_id>", methods=["POST"])
@flask_login.login_required
def comment_commit(post_id):
    if request.form["comment-text"]:
        text = request.form["comment-text"]

        POST_CONTENT_MIN_LENGTH = app.config["POST_CONTENT_MIN_LENGTH"]
        POST_CONTENT_MAX_LENGTH = app.config["POST_CONTENT_MAX_LENGTH"]

        if verification_utils.check(text, POST_CONTENT_MAX_LENGTH, POST_CONTENT_MIN_LENGTH, None):
            username = flask_login.current_user.username

            social_utils.create_comment(text, username, post_id)

            return redirect(url_for("content.post_content", post_id=post_id))
        else:
            return routes_utils.render_post_content(post_id, "Invalid text")
    else:
        return routes_utils.render_post_content(post_id, "Comment text can't be empty")


@content_.errorhandler(401)
def unauthorized(error):
    return redirect(url_for("auth.login"))

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <title>openSocial</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <span class="openSocial-title">
                    <a href="{{ url_for('content.home') }}">
                        openSocial
                    </a>
                </span>
                <span class="header-controls">
                    {% if not user_logged_in %}
                        <span class="login-control">
                            <a href="{{ url_for('auth.login') }}">
                                Login
                            </a>
                        </span>
                        <span class="register-control">
                             <a href="{{ url_for('auth.register') }}">
                                Register
                            </a>
                        </span>
                    {% else %}
                        <span class="username-header">
                            {{ username }}
                            <div class="dropdown-header-menu">
                                <span class="dropdown-header-item">
                                    <a href="{{ url_for('content.profile') }}">
                                        Profile
                                    </a>
                                </span>
                                <span class="dropdown-header-item">
                                    <a href="{{ url_for('content.post') }}">
                                        Post
                                    </a>
                                </span>
                                <span class="dropdown-header-item">
                                    <a href="{{ url_for('auth.logout') }}">
                                        Logout
                                    </a>
                                </span>
                            </div>
                        </span>
                    {% endif %}
                </span>
            </div>
            {% if error_message %}
                <div class="error_message-container">
                    {{ error_message }}
                </div>
            {% endif %}
            {% if success_message %}
                <div class="success_message-container">
                    {{ success_message }}
                </div>
            {% endif %}
            <div class="main-content">
                <div class="posts-container">
                    {% if posts|length == 0 %}
                        <p>
                            No posts to show
                        </p>
                    {% endif %}
                    {% for post in posts %}
                        <div class="post-container">
                            <div class="post-header">
                                <h2>
                                    <a href="{{ url_for('content.post_content', post_id=post.id) }}">
                                        {{ post.title }}
                                    </a>
                                </h2>
                            </div>
                            <div class="post-content">
                                {{ post.content }}
                            </div>
                            <div class="post-footer">
                                <p>
                                    Posted by {{ post.author_name }}
                                </p>
                                <p>
                                    Posted at {{ post.date_posted }}
                                </p>
                                <p>
                                    Comments {{ post.comments|length }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="footer">
                openSocial ~ Built with Flask
            </div>
        </div>
    </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <title>openSocial</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <span class="openSocial-title">
                    <a href="{{ url_for('content.home') }}">
                        openSocial - Login
                    </a>
                </span>
            </div>
            <div class="content">
                <div class="auth-container">
                    <div class="auth-form">
                        <form method="POST" action="/login/process">
                        <input type="text" name="name" placeholder="Username...">
                        <input type="password" name="password" placeholder="Password...">
                        <input type="submit" value="Login">
                    </form>
                    {% if error_message %}
                        <div class="error_message-container">
                            {{ error_message }}
                        </div>
                    {% endif %}
                    </div>
                </div>
            </div>
            <div class="footer">
                openSocial ~ Built with Flask
            </div>
        </div>
    </body>
</html>

templates/post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <title>openSocial</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <span class="openSocial-title">
                    <a href="{{ url_for('content.home') }}">
                        openSocial - Post
                    </a>
                </span>
                <span class="header-controls">
                    <span class="username-header">
                        {{ username }}
                        <div class="dropdown-header-menu">
                            <span class="dropdown-header-item">
                                <a href="{{ url_for('content.profile') }}">
                                    Profile
                                </a>
                            </span>
                            <span class="dropdown-header-item">
                                <a href="{{ url_for('content.post') }}">
                                    Post
                                </a>
                            </span>
                            <span class="dropdown-header-item">
                                <a href="{{ url_for('auth.logout') }}">
                                    Logout
                                </a>
                            </span>
                        </div>
                    </span>
                </span>
            </div>
            <div class="content">
                <div class="post-form-container">
                    <div class="post-form-form">
                        <form action="/post/commit" method="POST">
                            <input type="text" name="post-title" placeholder="Post title...">
                            <textarea placeholder="Post text..." name="post-text"></textarea>
                            <input type="submit" value="Post">
                        </form>
                        {% if error_message %}
                            <div class="error_message-container">
                                {{ error_message }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="footer">
                openSocial ~ Built with Flask
            </div>
        </div>
    </body>
</html>

templates/post_content.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <title>openSocial</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <span class="openSocial-title">
                    <a href="{{ url_for('content.home') }}">
                        openSocial
                    </a>
                </span>
                <span class="header-controls">
                    <span class="username-header">
                        {{ username }}
                        <div class="dropdown-header-menu">
                            <span class="dropdown-header-item">
                                <a href="{{ url_for('content.profile') }}">
                                    Profile
                                </a>
                            </span>
                            <span class="dropdown-header-item">
                                <a href="{{ url_for('content.post') }}">
                                    Post
                                </a>
                            </span>
                            <span class="dropdown-header-item">
                                <a href="{{ url_for('auth.logout') }}">
                                    Logout
                                </a>
                            </span>
                        </div>
                    </span>
                </span>
            </div>
            <div class="main-content">
                <div class="posts-container">
                    <div class="post-container">
                        <div class="post-header">
                            <h2>
                                {{ post.title }}
                            </h2>
                        </div>
                        <div class="post-content">
                                {{ post.content }}
                        </div>
                        <div class="post-footer">
                            <p>
                                Posted by {{ post.author_name }}
                            </p>
                            <p>
                                Posted at {{ post.date_posted }}
                            </p>
                            <p>
                                Comments {{ post.comments|length }}
                            </p>
                        </div>
                    </div>
                     <div class="comments-container">
                         {% if post.comments|length == 0 %}
                         <div class="comment-container">
                             No comments yet
                         </div>
                         {% endif %}
                         <div class="post-form-container">
                            <div class="post-form-form">
                                <form action="{{ url_for('content.comment_commit', post_id=post.id) }}" method="POST">
                                    <textarea placeholder="Comment text..." name="comment-text"></textarea>
                                    <input type="submit" value="Comment">
                                </form>
                                {% if error_message %}
                                    <div class="error_message-container">
                                        {{ error_message }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                         {% for comment in comments %}
                             <div class="comment-container">
                                <div class="comment-content">
                                        {{ comment.content }}
                                </div>
                                <div class="comment-footer">
                                    <p>
                                        Posted by {{ comment.author_name }}
                                    </p>
                                    <p>
                                        Posted at {{ comment.date_posted }}
                                    </p>
                                </div>
                             </div>
                         {% endfor %}
                     </div>
                </div>
            </div>
            <div class="footer">
                openSocial ~ Built with Flask
            </div>
        </div>
    </body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <title>openSocial</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <span class="openSocial-title">
                    <a href="{{ url_for('content.home') }}">
                        openSocial - Profile
                    </a>
                </span>
                <span class="header-controls">
                    <span class="username-header">
                            {{ username }}
                            <div class="dropdown-header-menu">
                                <span class="dropdown-header-item">
                                    <a href="{{ url_for('content.profile') }}">
                                        Profile
                                    </a>
                                </span>
                                <span class="dropdown-header-item">
                                    <a href="{{ url_for('content.post') }}">
                                        Post
                                    </a>
                                </span>
                                <span class="dropdown-header-item">
                                    <a href="{{ url_for('auth.logout') }}">
                                        Logout
                                    </a>
                                </span>
                            </div>
                        </span>
                    </span>
                </span>
            </div>
            <div class="content">
                Hello {{ username }}
            </div>
            <div class="footer">
                openSocial ~ Built with Flask
            </div>
        </div>
    </body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <title>openSocial</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <span class="openSocial-title">
                    <a href="{{ url_for('content.home') }}">
                        openSocial - Register
                    </a>
                </span>
            </div>
            <div class="content">
                <div class="auth-container">
                    <div class="auth-form">
                        <form method="POST" action="/register/process">
                            <input type="text" name="name" placeholder="Username...">
                            <input type="password" name="password" placeholder="Password...">
                            <input type="submit" value="Register">
                        </form>
                        {% if error_message %}
                            <div class="error_message-container">
                                {{ error_message }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="footer">
                openSocial ~ Built with Flask
            </div>
        </div>
    </body>
</html>